# line length
error_on_line_overflow = true
max_width = 80

# comments
comment_width = 100
wrap_comments = false # rustfmt is broken currently and doesn't softwrap
normalize_comments = false

# commas
trailing_comma = "Never"
match_block_trailing_comma = true

# code
use_try_shorthand = true
binop_separator = "Back"
format_strings = false # rustfmt string handling is horribly busted

# imports
reorder_imports = true
