language: rust
rust:
  - stable
sudo: false
cache: cargo
# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - dbus
notifications:
  slack:
    rooms:
      - way-cooler:W2vOSvJvgxGi7EiGkZCtvlB6#way-cooler
    on_success: :change
    on_failure: :change
  email: false
# load travis-cargo
before_script:
  - | 
      git clone https://github.com/Timidger/travis-cargo
      (cd travis-cargo;
      pip install -e . --user &&
      export PATH=$HOME/.local/bin:$PATH)
script:
  - export DBUS_NO_PKG_CONFIG=true
  - export DBUS_1_NO_PKG_CONFIG=true
  - cargo test --verbose

after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify --exclude-pattern="main.rs,mod.rs,tests.rs,wayland_client_api.rs,callbacks.rs"
